name: Run auto renew script

on:
  schedule:
    # 这里是每12小时触发一次，CRON 表达式
    - cron: "0 */12 * * *"  # 每12小时执行一次
  workflow_dispatch:  # 也允许手动触发工作流

jobs:
  run_script:
    runs-on: ubuntu-latest  # 选择 GitHub Actions 运行环境
    env:
      PYTHONUTF8: 1  # 强制Python使用UTF-8编码
      PYTHONIOENCODING: utf-8

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # 设置 Python 版本

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 假设你有一个 requirements.txt 文件，包含所需的依赖

      # 运行脚本
      - name: Run auto renew script
        run: python auto_renew.py
